AllCops:
  TargetRubyVersion: 2.3

Layout/EndOfLine:
  EnforcedStyle: lf

# Can't add block parameter type annotations with this rule.
Layout/MultilineBlockLayout:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
