notifications:
  email: false

before_script:
  - mkdir -v "${out=_site}" && cd "$_"
  - echo "https://$GITHUB_TOKEN:@github.com" > ~/.git-credentials
  - git clone -n https://github.com/"$TRAVIS_REPO_SLUG" .
      -c user.name=Travis
      -c user.email=bilge+travis@scriptfusion.com
      -c credential.helper=store

  - # Checkout remote branch or create new branch if remote branch doesn't exist yet.
    git checkout "${branch=gh-pages}"
      || git checkout --orphan "$branch"

  - rm -rfv *

script:
  - cd - && bundler exec jekyll b

after_success:
  - cd "$out" &&
    git add -A . &&
    git commit -m "Built from $TRAVIS_COMMIT." &&
    git push origin HEAD:"$branch"
