title: ScriptFUSION PHP project status
repository_url: https://github.com/ScriptFUSION/Status
build_url: http://travis-ci.org/ScriptFUSION/Status

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
