title: ScriptFUSION PHP project status
repository_url: https://github.com/ScriptFUSION/Status
build_url: https://github.com/ScriptFUSION/Status/actions/workflows/CD.yml
badge_url: https://github.com/ScriptFUSION/Status/workflows/CD/badge.svg

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
